### PR TITLE
Fixes issue of not propagating events and issue of selected value not a string

### LINKED ISSUE #11: Unable to submit autocomplete form when table column is bigint(20)
**Rails 4.2.0, Mysql 5.5**

We have a search bar looking for telephone numbers. In our table, the field `tn` is type `bigint(20)`. I am able to use autocomplete to find a list of matching entries. When I try to click on an entry, I get the following the dev tools console:

```
TypeError: n.item.value.toLowerCase is not a function
autocomplete-rails.js:1:2138
```

Of course, the issue is the generated JS file trying to perform a string method on a bigint.  I do not want to remove this method, as most of our search boxes contain alphanumeric characters. (This is the only instance, right now, of searching for a number.)

FWIW, here is the JavaScript I am using to submit the form when selecting a list item:

```js
$('#did_tn').bind('railsAutocomplete.select', function(event, data) {
  $('#did_select').submit();
});
```

### PR DESCRIPTION
**Pull request by codenamev**
This fixes two issues that we have come across:

1. Selecting a result does not trigger `change` events for related input values as would be expected
2. Result values may contain non-string (e.g. in our case integer) values (#11)

We've updated the minified js as well with these fixes.

Closes #11

### CODE REVIEW

**Comment by onebree** [comment]
Does this handle #11? If so, thank you!

**Comment by codenamev** [comment]
yup :smiley:

**Comment by onebree** [comment]
:+1: Only suggestion, add the plain text `Closes #11` to your top comment of this pull request. It will automatically close my issue. :-)

**Comment by bigtunacan** [comment]
@codenamev Thanks.

**Comment by onebree** [comment]
@codenamev Is it possible you write some tests proving this behavior? I do not want to update them gem and change my controllers before I know it works.

**Pull request merged**
